### ISSUE TITLE
About Github Discussion

### ISSUE THREAD

**Issue by Polpetta** [PackageFoundation/yap#14]
@M0Rf30 do you think it is worth trying them?

I mean we could have everything in one place. Tell me what is your opinion about it!

**Comment by M0Rf30** [comment]
Yes of course! My main concern is about "doubling" communication channels. Because we are a little team, at least for now, could be more useful to focus on few of them. For example: we have matrix channel, tg, slack ones. do you have time to manage all of them?

**Comment by Polpetta** [comment]
Yeah I would be KISS too!

So I was thinking of keeping Matrix for community, Discussions here for who prefers forum-like approach, and if we want we can create a Telegram channel that will be automatically managed by Github Actions and it will notify every time there is a new release...otherwise for me we can keep Matrix & Discussion for community related stuff! I think it is enough to start :grin:

**Comment by M0Rf30** [comment]
Ok sounds good to me. we can report the progress here or with the use of Projects tab, in order to give visibility of milestones and whatever

**Comment by Polpetta** [comment]
Yeah sounds great :call_me_hand:

**Comment by Polpetta** [comment]
I've enabled Github Discussion. I think we can close that now.
