### ISSUE TITLE
Artifacts are generated both in the PKGBUILD folder and in the destination folder

### ISSUE THREAD

**Issue by apontini** [PackageFoundation/yap#18]
**Describe the bug**
Artifacts are generated both in the PKGBUILD folder and in the destination folder

**To Reproduce**
Run yap with a destination folder that's not the same as the PKGBUILD folder 

**Expected behavior**
I should only have artifacts on the destination folder as a result of the build

**Logs**
No useful logs

**Desktop:**
 - OS: Parrot linux
 - Version 5.0 LTS

**Additional context**
I found this when I generated deb and rpm artifacts: these were created in the PKGBUILD directory
and in the output directory. I expect to find a single output at the end of the process. The command I
executed to test this behaviour was `cd examples && go run ../main.go build ubuntu`. If you run this,
you'll see two artifacts being generated

**Comment by M0Rf30** [comment]
can you add more details on the executed command/flow? you can also edit the additional context field

**Comment by apontini** [comment]
@M0Rf30 done, is it enough?

**Comment by M0Rf30** [comment]
the command that should work is 
`cd examples && sudo  go run ../main.go build your-host .`

without sudo you can't conitnue. 
your-host iit's because outside the container you can only build for your host XD

you should use something like:

`docker run -ti -v $(pwd):/project packagefoundation/yap-ubuntu-bionic:latest build ubuntu-bionic examples/`

**Comment by apontini** [comment]
>without sudo you can't conitnue.
>your-host iit's because outside the container you can only build for your host XD

Yes I'm aware of that! But it manages to generate packages without the need to resort to rebuilding the docker image every time, so I went with it. Besides, this also happens when using docker IIRC (at least, on pacur).

**Comment by M0Rf30** [comment]
Please pass the checks are and it's good to me :tada:

**Comment by Polpetta** [comment]
Yeah, this unfortunately is a know bug I introduced when implementing the multi-project build. I forgot to clean that up :sweat_smile:

**Comment by apontini** [comment]
Dude, cringe.
