### ISSUE TITLE
[Error] Docker images don't build correctly

### ISSUE THREAD

**Issue by Polpetta** [PackageFoundation/yap#47]
**Describe the bug**
The docker images are under `docker/<distro>/Dockerfile` but inside of the definition there's `COPY . /project`, and they copy an empty folder. Image builds successfully, but there's not `yap` inside it

**To Reproduce**
```sh
# From the project root
(cd docker/ubuntu-focal/ && docker build -t test/test -f Dockerfile .)
```

**Expected behavior**
```
docker run --rm -it test/test            
Yap allows building packages for multiple GNU/Linux distributions with a
consistent package spec format.

Complete documentation is available at
🌐 https://github.com/packagefoundation/yap

Usage:
  yap [command]

Available Commands:
  build        Build multiple PKGBUILD definitions within a yap.json or pacur.json project
  completion   Generate completion script
  docker       Pull the built images
  help         Help about any command
  list-targets List a bunch of available build targets
  version      Print the version number of Yap

Flags:
  -h, --help   help for yap

Use "yap [command] --help" for more information about a command.
```

**Logs**
Logs for `cd docker/ubuntu-focal/ && docker build -t test/test -f Dockerfile . 2>&1 | tee /tmp/bug.log`
I've attached them here [bug.log](https://github.com/PackageFoundation/yap/files/10083841/bug.log). Note that there's an additional `apt` error, we forgot a `-y` flag :sweat_smile: 

**Desktop (please complete the following information):**

- OS: Arch man
- Version `Linux davide-notebook 6.0.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 10 Nov 2022 21:14:24 +0000 x86_64 GNU/Linux`

Finally, I put the `Dockerfile` in the root of the project and built it and it works in that case

**Comment by M0Rf30** [comment]
to manage the build and the containerization of the binary file, the correct (and working instruction), should be"
```
docker build . -f docker/ubuntu-focal//Dockerfile -t packagefoundation/yap-ubuntu-focal:latest
```
from the root of this repo
